<div data-bind="scope: 'weather'"><!-- ko template: getTemplate() --><!-- /ko --></div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "weather": {
                        "component": "Slipushkin_Weather/js/weather",
                        "template": "Slipushkin_Weather/weather",
                        "cities": <?= $block->getViewModel()->getCitiesAsJson() ?>
                    }
                }
            }
        }
    }
</script>
